---

- name: "{{msg_prefix}} - Building {{container.image}}:{{container.version}}"
  shell: docker build {{'--pull' if container.pull else ''}} -t {{container.image}}:{{container.version}} .
  args:
    chdir: "{{container.basedir+'/'+container.directory}}"
  register: container_build

- name: "{{msg_prefix}} - New image ID"
  set_fact:
    container_image_id_new: "{{container_build.stdout|regex_replace('^Successfully built (.*)$', '\\1')}}"
  when: container_build has changed

- name: "{{msg_prefix}} - Push new image"
  shell: docker tag {{container.image}}:{{container.version}} {{container.registry}}/{{container.image}}:{{container.version}} && docker push {{container.registry+'/'+container.image}}
  args:
    chdir: "{{container.basedir+'/'+container.directory}}"
  when: container.push and container_build has changed and container_image_id_new != ""

