---

- name: "{{cname}} - Set container variable"
  set_fact:
    container: "{{containers[cname]}}"
    msg_prefix: "| {{cname}} @ {{ansible_hostname|lower}} |"

- name: "{{msg_prefix}} - Assert required variables"
  fail:
    msg: >
      --> '{{item}}' variable is not defined!
      Requied variables:
      name, directory, image, ...
  with_items: "{{container_required_vars}}"
  when: container[item] is not defined

- name: "{{msg_prefix}} - Assert either 'create' OR 'restart' may be yes/true"
  fail:
    msg: "'create' and 'restart' are mutually exclusive!"
  when: container.create is defined and container.create and container.restart is defined and container.restart

- name: "{{msg_prefix}} - Assert 'pull' OR 'build' must be defined"
  fail:
    msg: "either 'pull' or 'build' must be defined!"
  when: container.pull is not defined and container.build is not defined

- name: "{{msg_prefix}} - Assert directory must be defined"
  fail:
    msg: "'container_default_basedir' and/or container 'directory' variable are not set!"
  when: container_default_basedir == "" or container.directory == ""

